### ISSUE TITLE
Music doesn't play at all

### ISSUE THREAD

**Issue by xSkyler1** [eerussianguy/Combat-Music#3]
Yes, I changed the config, I placed a texturepack to overwrite pigstep.ogg, but yet, it just, doesn't play anything, not even the original pigstep, it doesn't play the music when I take damage or anything

**Comment by xSkyler1** [comment]
Also, yes I have edited the config, the range is locked at 1, it just makes a backup file instead or something like that

![image](https://user-images.githubusercontent.com/103153352/162200836-654c253f-539c-4594-ad88-776c3164b296.png)

**Comment by eerussianguy** [comment]
read the log file to see if your inputs are going in correctly.
